// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1N3EkU-0rpFilk_omBuMAArtL9xKK1n8',
    appId: '1:275816093013:web:e4df1e1c5081a435f28bdc',
    messagingSenderId: '275816093013',
    projectId: 'myevent-ae119',
    authDomain: 'myevent-ae119.firebaseapp.com',
    storageBucket: 'myevent-ae119.appspot.com',
    measurementId: 'G-RHKVY7G0MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1-lcZFkX22zD8dBb9JUi0EI46NPV3ja8',
    appId: '1:275816093013:android:ebb0c65662eb1d3ff28bdc',
    messagingSenderId: '275816093013',
    projectId: 'myevent-ae119',
    storageBucket: 'myevent-ae119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYtStI2QCLNuoPrX7LA9bp1s2nNt-Tsg',
    appId: '1:275816093013:ios:69b7e3c10b0d7ac7f28bdc',
    messagingSenderId: '275816093013',
    projectId: 'myevent-ae119',
    storageBucket: 'myevent-ae119.appspot.com',
    iosBundleId: 'com.app.myEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYtStI2QCLNuoPrX7LA9bp1s2nNt-Tsg',
    appId: '1:275816093013:ios:b1d6b4b2df306880f28bdc',
    messagingSenderId: '275816093013',
    projectId: 'myevent-ae119',
    storageBucket: 'myevent-ae119.appspot.com',
    iosBundleId: 'com.app.myEvent.RunnerTests',
  );
}
